# We want `ocaml`, `opam`, and the `biokepi` user:
FROM hammerlab/biokepi-run:More-Dockerfile-improvements

ENV CLOUDSDK_CORE_DISABLE_PROMPTS true
RUN bash -c 'curl https://sdk.cloud.google.com | bash'

